services:
  - type: web
    name: gg-checker-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_checker:app --host=0.0.0.0 --port=10000"